### ISSUE TITLE
Implementing advanced formatting

### ISSUE THREAD

**Issue by jombard** [nuxt-community/dayjs-module#127]
dayjs documentation says to add library as such:

`var advancedFormat = require('dayjs/plugin/advancedFormat')`
`dayjs.extend(advancedFormat)`
`dayjs().format('Q Do k kk X x')`

What is the best way to add the advanced format plugin to dayjs library in nuxt project?

Library is added in nuxt.config
`modules: {
      'nuxt-dayjs-module'
}`

This adds dayjs to root instance in components. ie: this.dayjs

Have tried importing the plugin in a component but this does not work.

Any advice appreciated!

**Comment by nathanchase** [comment]
I just added the plugin directly on the component that needed it, and it works just fine.

```
<template>
  <span v-text="$dayjs(unformattedDate).format('MMMM Do, YYYY')" /> // returns 'June 1st, 2020'
</template>

<script>
import advancedFormat from 'dayjs/plugin/advancedFormat';

export default {
  data() { 
    return { unformattedDate: '2020-06-01' };
  },

  created() {
    this.$dayjs.extend(advancedFormat);
  },
}
</script>
```

**Comment by strotgen** [comment]
If you are looking to do it globally and not for every componen, you can create a _dayjs.js_ file in the plugins directory with the following:

```js
import customParseFormat from 'dayjs/plugin/customParseFormat'

export default ({ app: { $dayjs } }) => {
  $dayjs.extend(customParseFormat)
}
```

and add it to your nuxt config file

**Comment by nathanchase** [comment]
@strotgen Yep, I did something similar, although I explicitly injected the method like so:

```
// dayjs.js

import dayjs from 'dayjs';
import advancedFormat from 'dayjs/plugin/advancedFormat';

dayjs.extend(advancedFormat);

const calendarDate = date => {
  return dayjs(date).format('MMMM Do, YYYY');
};

export default ({ app }, inject) => {
  inject('calendarDate', calendarDate);
};
```
and then anywhere in my app I can just call `this.$calendarDate(dateValue)`.

**Comment by jombard** [comment]
Thank you for the solutions. In light of this is it worth updating the README to help others in the same situation?

**Comment by potato4d** [comment]
I will now attempt to support that. Please be patient for a while longer as I will be conducting an investigation.

**Comment by fmctaggart** [comment]
I've added it into Nuxt config as per the documentation and it works. I think this issue can be closed now.
`modules: ['@nuxtjs/dayjs',],
 dayjs: {
    plugins: ['advancedFormat'], 
  },`
