### ISSUE TITLE
Moving to nuxt-community

### ISSUE THREAD

**Issue by pi0** [nuxt-community/dayjs-module#156]
Hi @potato4d 😊

If you are interested in moving your awesome module to `nuxt-community` and `@nuxtjs/` that's more than welcome. You still will be code owner and maintainer of course just a little bit more official and others can discover/trust it easier and help for maintenance.

**Comment by potato4d** [comment]
@pi0 
I would love to move!
Could you please email me at mail@potato4d.me or Twitter @ potato4d for detailed instructions?

**Comment by potato4d** [comment]
Done.
