### ISSUE TITLE
Plugins support?

### ISSUE THREAD

**Issue by lennoximus** [nuxt-community/dayjs-module#182]
Evening!
Can you enable `dayjs` plugins (e.g. `customParseFormat`) in the current implementation of the module?
Thanks in advance.

**Comment by strotgen** [comment]
While they add the option to add plugins globally, you can create a _dayjs.js_ file in the plugins directory with the following:

```js
// use the plugin you want, this is just an example
import customParseFormat from 'dayjs/plugin/customParseFormat'

export default ({ app: { $dayjs } }) => {
  $dayjs.extend(customParseFormat)
}
```

and add it to your nuxt config file.

**Comment by potato4d** [comment]
I will now attempt to support that. Please be patient for a while longer as I will be conducting an investigation.

**Comment by lennoximus** [comment]
Sure, you can make your plugin to include extensions you need, but  there is no point in your own plugin if we already have one in this package, in my opinion.

Needless to say, I was asking this particular question rather for a free PR myself if this functionality isn't working out of the box than for a workaround solution.

I can either work something out or @potato4d can take the lead in this, if you want so.

**Comment by potato4d** [comment]
#208

**Comment by potato4d** [comment]
v1.2.0 is now available :tada:
