### ISSUE TITLE
Use $dayjs with Vue.mixin

### ISSUE THREAD

**Issue by hmaesta** [nuxt-community/dayjs-module#189]
How can I use `$dayjs` with a `Vue.mixin`?

#### Steps:
1. Installed: `yarn add @nuxtjs/dayjs`
2. Added `'@nuxtjs/dayjs'` to `modules: []` in `nuxt.config.js`
3. Created `dayjs.js` in `/plugins`
4. Added `{src: '~/plugins/dayjs'},` to `plugins: []` in `nuxt.config.js`

#### dayjs.js
```js
import Vue from 'vue'

Vue.mixin({
  methods: {

    format_date: function (date) {
        return this.$dayjs(date).format('L');
    }

  }
})
```

**Comment by potato4d** [comment]
Vue.mixin will no longer be supported as it will be replaced by Composition API.
