### ISSUE TITLE
on nuxtjs not work.

### ISSUE THREAD

**Issue by xiongsongsong** [nuxt-community/dayjs-module#237]
![image](https://user-images.githubusercontent.com/342509/96408480-2ee0d880-1216-11eb-98fa-02baa89b4245.png)

This has been set up according to the documentation.

**Comment by potato4d** [comment]
_We_ will respond within a day or two.

**Comment by potato4d** [comment]
@xiongsongsong

Please provide the URL of the smallest reproducing codesandbox.

**Comment by xiongsongsong** [comment]
ok. https://codesandbox.io/s/musing-rosalind-p1jjh?file=/pages/index.vue

**Comment by potato4d** [comment]
thanks.

This appears to be an issue in combination with AntdDayjsWebpackPlugin.

**Comment by potato4d** [comment]
The Day.js plugin seems to be working correctly
https://codesandbox.io/s/sharp-vaughan-wgci4?file=/pages/index.vue
