### ISSUE TITLE
TS2339: Property 'weekdays' does not exist on type 'typeof dayjs'.

### ISSUE THREAD

**Issue by chemscobra** [nuxt-community/dayjs-module#247]
I'm getting this console error when I use this.$dayjs.**weekdays**() even though i added the corresponding dayjs type into de tsconfig like so:

```
"types": [
      "@types/node",
      "@nuxt/types",
      "@nuxtjs/dayjs",
      "@nuxtjs/axios",
      "./types/"
    ]
```

**Comment by potato4d** [comment]
@chemscobra 
Please provide the minimum URL to Codesandbox that would reproduce the problem.
Also, did you know that weekdays in Day.js is not core, but a plugin?

**Comment by chemscobra** [comment]
here is the url [sandbox](https://codesandbox.io/s/suspicious-tereshkova-rcezs). and Yes I added localeData in the plugins for the optional dayjs options like so:

dayjs: {
    locales: ['en'],
    defaultLocale: 'en',
    plugins: ['localeData'] // Your Day.js plugin
  }

**Comment by tiretdusix** [comment]
Hello.

`.weekday() ` requires the `Weekday` plugin. https://day.js.org/docs/en/plugin/weekday

You can create a nuxt.js plugin to enable day.js plugins like @strotgen and @nathanchase  [show in issue](https://github.com/nuxt-community/dayjs-module/issues/127#issuecomment-646857016) #127

**Comment by chemscobra** [comment]
Hello @tiretdusix thanks a lot for your answer but I'm actually using weekdays() from the [LocaleData](https://day.js.org/docs/en/plugin/locale-data.`) Plugin to list the weekdays names. I've manage to solve the issue creating a nuxt plugin like you indicated.

**Comment by potato4d** [comment]
Dirty solution, but the problem with type definitions can be solved with

I'm currently investigating if this can be solved by a plugin!

```
<template>
  <div>{{value}}</div>
</template>

<script lang="ts">
import Vue from 'vue'
import weekdays from 'dayjs/plugin/weekdays' // import dayjs/plugin/weekdays.d.ts

export default Vue.extend({
  computed: {
    value() {
      return this.$dayjs().weekday(-7)
    }
  }
})
</script>
```
