### ISSUE TITLE
Document how to add a plugin

### ISSUE THREAD

**Issue by Soviut** [nuxt-community/dayjs-module#252]
Currently the README shows an example nuxt.config.js but the plugins array is empty. It would be good to expand on this example by adding an example of how to include a plugin.

**Comment by potato4d** [comment]
@Soviut 

Almost done!
https://github.com/nuxt-community/dayjs-module#1-register-dayjs-module-to-your-nuxt-application

**Comment by potato4d** [comment]
since v1.2.1

**Comment by Soviut** [comment]
Thanks, it looks good.
