### ISSUE TITLE
Must be use TimeZone plugin?

### ISSUE THREAD

**Issue by kazuemon** [nuxt-community/dayjs-module#270]
( メインコントリビューターの方は日本の方ですが一応英語で送ります )

## The Problem
```
Cannot read property 'setDefault' of undefined
```
![image](https://user-images.githubusercontent.com/12812934/103339840-d8213600-4ac5-11eb-9bbe-787d9652519b.png)

## Steps to Reproduce
- Set Config 
```
dayjs: {
    locales: ['en', 'ja'],
    defaultLocale: 'en',
    defaultTimeZone: 'Asia/Tokyo',
    plugins: ['utc'],
},
```

**Comment by lopermo** [comment]
I still get the same error. It doesn't look like it's solved. Any ETA on this?
