### ISSUE TITLE
Typescript support for dayjs with Plugins

### ISSUE THREAD

**Issue by solidevolution** [nuxt-community/dayjs-module#295]
Hello,

I added dayjs to next with this module and configured it as follow:

```
  dayjs: {
    locales: ['de', 'en'],
    defaultLocale: 'de',
    defaultTimeZone: 'Europe/Berlin',
    plugins: ['utc', 'timezone', 'localizedFormat'],
  },
```

If I use 

`return this.$dayjs().tz(this.$store.state.user.timezone).format('LLL ZZ')`

in a component, I get the following typescript error

`Property 'tz' does not exist on type 'Dayjs'.Vetur(2339)`

My workaround is

`return (this.$dayjs() as any).tz(this.$store.state.user.timezone).format('LLL ZZ')`

currently but I normally try to eliminate all any's in my projects.

Is there further typescript support?

PS: Of course I added nuxtjs/dayjs to the typescript types configuration.

**Comment by ibiliskov** [comment]
@solidevolution You could write `import 'dayjs/plugin/timezone'` at the component where you use `$dayjs.tz`. This will cause side effect of declaring methods on Dayjs class (check `dayjs/plugin/timezone.d.ts` -> it augments `Dayjs` interface with `tz` and `offsetName`)
