### ISSUE TITLE
Set defaultTimeZone from store?

### ISSUE THREAD

**Issue by jb-alvarado** [nuxt-community/dayjs-module#299]
Hello,

is it possible to set the default time zone globally out side from nuxt.config.js?

For example, in my config I have:

```javascript
dayjs: {
        locales: ['en', 'de'],
        defaultLocale: 'en',
        defaultTimeZone: 'UTC',
        plugins: [
            'utc',
            'timezone'
        ]
    }
```

But on page load I want to override the default time zone with: `this.$dayjs.tz.setDefault('Europe/Berlin')`.

**Comment by potato4d** [comment]
```
dayjs: {
        locales: ['en', 'de'],
        defaultLocale: 'en',
        defaultTimeZone: 'Europe/Berlin',
        plugins: [
            'utc',
            'timezone'
        ]
    }
```

？

**Comment by jb-alvarado** [comment]
Thank you, but this is not what I wanted. But I think now defaultTimeZone is in general not the right setting. I use now:

```
this.$dayjs().tz(timezone)
```
This works in my case.

**Comment by potato4d** [comment]
thanks
