### ISSUE TITLE
Locales and defaultLocale

### ISSUE THREAD

**Issue by gldkru** [nuxt-community/dayjs-module#303]
Hey! Thanks for your module

I have set default locale and locales, but who should switch them and where?

```js
    ...
    locales: ['ru', 'en'],
    defaultLocale: 'en',
```

OK, i18n module changed language, what's next?

**Comment by shakhzodkudratov** [comment]
same here, help me too

**Comment by shakhzodkudratov** [comment]
hey dude, here is it. add this to nuxt.config.js -> plugins array:

```
export default function ({ i18n, $dayjs }) {
  i18n.beforeLanguageSwitch = (oldLocale, newLocale) => {
    $dayjs.locale(newLocale)
  }
}
```
