### ISSUE TITLE
Nuxt3 Support

### ISSUE THREAD

**Issue by acidjazz** [nuxt-community/dayjs-module#376]
If I get more time I will make this a PR.

I have written a DayJS plugin for nuxt3 and so far its working pretty well:

`plugnis/dayjs.ts`

```ts
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime.js'
import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin((nuxtApp) => {
  dayjs.extend(relativeTime)
  nuxtApp.provide('dayjs', dayjs)
})

declare module '#app' {
  interface NuxtApp {
    $dayjs: dayjs.Dayjs
 }
}
```

I assume next steps are to transfer this into the template/runtime format and plug in the locale config.

**Comment by potato4d** [comment]
Very much looking forward to you sending me your PR!

**Comment by avxkim** [comment]
Is there a work in progress?

**Comment by wobsoriano** [comment]
Well if you really need to use it now you can just create a plugin

```ts
// ~/plugins/dayjs.ts
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import localizedFormat from 'dayjs/plugin/localizedFormat';
import updateLocale from 'dayjs/plugin/updateLocale';

dayjs.extend(relativeTime);
dayjs.extend(localizedFormat);
dayjs.extend(updateLocale);
// OTHER PLUGINS

export default defineNuxtPlugin(() => {
  return {
    provide: {
      dayjs,
    },
  };
});
```

```html
<script setup lang="ts">
const { $dayjs } = useNuxtApp();
</script>

<template>
  <div>
    Now: {{ $dayjs() }}
  </div>
</template>
```

**Comment by safejace** [comment]
so when using this plugin, when i try to run `yarn build` or `yarn generate` then `yarn preview` i get this error:

```
[nuxt] [request error] Cannot find module '/Users/thejacer87/Development/safecom-fmeuc/.output/server/node_modules/dayjs/plugin/utc' imported from /Users/thejacer87/Development/safecom-fmeuc/.output/server/chunks/app/server.mjs
Did you mean to import dayjs/plugin/utc.js?
  at new NodeError (node:internal/errors:371:5)  
```
  
Not sure if it's a nuxt issue or dayjs?

**Comment by acidjazz** [comment]
> so when using this plugin, when i try to run `yarn build` or `yarn generate` then `yarn preview` i get this error:
> 
> ```
> [nuxt] [request error] Cannot find module '/Users/thejacer87/Development/safecom-fmeuc/.output/server/node_modules/dayjs/plugin/utc' imported from /Users/thejacer87/Development/safecom-fmeuc/.output/server/chunks/app/server.mjs
> Did you mean to import dayjs/plugin/utc.js?
>   at new NodeError (node:internal/errors:371:5)  
> ```
> 
> Not sure if it's a nuxt issue or dayjs?

I haven't tested my version of the nuxt3 plugin with a static-compiled version yet - maybe try adding the `.js` ?

**Comment by Developer27149** [comment]
We need it.thanks!

**Comment by nathanchase** [comment]
I've created a Nuxt 3 module using the official Nuxt 3 module builder: 
https://github.com/nathanchase/dayjs/

It's on npm currently at: https://www.npmjs.com/package/@nathanchase/nuxt-dayjs-module

I wasn't sure the protocol of how to submit this as a PR for this module. You can check [the playground for examples of the module working](https://github.com/nathanchase/dayjs/blob/master/playground/app.vue).

**Comment by nathanchase** [comment]
> I've created a Nuxt 3 module using the official Nuxt 3 [module-builder](https://github.com/nuxt/module-builder): https://github.com/nathanchase/dayjs/

Well, I'm having some issue when actually using the module in Nuxt 3 where I get an error:
`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/dayjs.min.js?v=e84ee87d' does not provide an export named 'default' (at plugin.mjs:1:8)`
, although the module's playground itself works perfectly fine...

**Comment by nathanchase** [comment]
OK! Got it working! v1.07 - Now also supports configuration in nuxt.config, like:
```js
dayjs: {
    plugins: [
      'duration',
      'relativeTime',
      'advancedFormat',
      'weekday'
    ]
}
```

**Comment by potato4d** [comment]
working at https://github.com/nuxt-community/dayjs-module/tree/next

**Comment by JoaoPedroAS51** [comment]
Hi @potato4d! I was working on a Nuxt 3 version of this module a while ago. Would you be interested in taking a look?

**Comment by CaptainFalcon92** [comment]
@potato4d I sure am interested. Any status on this ?
The doc does not mention anything yet so i assume it is still in the making

**Comment by acidjazz** [comment]
I am working on an official nuxt3 module that will be live next week @Dodje, i will close this issue with its URL ASAP

**Comment by acidjazz** [comment]
@Dodje @Developer27149 @safejace @avxkim 

https://github.com/fumeapp/dayjs
